version: '3.8'
services:
  parquet-export:
    image: mekomsolutions/flink-parquet-export
    depends_on:
     - postgresql
    environment:
      JDBC_URL: jdbc:postgresql://postgresql:5432/analytics
      JDBC_USERNAME: analytics
      JDBC_PASSWORD: password
      LOCATION_TAG: location1
    volumes:
      - ./data/parquet:/parquet