blob:
  server:
    port: '6124'
state:
  checkpoints:
    num-retained: 2
    dir: s3://flink-state-bucket/checkpoints/
  savepoints:
    dir: s3://flink-state-bucket/savepoints/
  backend:
    type: rocksdb
    incremental: true
restart-strategy:
  type: exponential-delay
jobmanager:
  rpc:
    address: 8092b85a99d2
    port: 6123
  memory:
    process:
      size: 3g
    jvm-metaspace:
      size: 1g
metrics:
  reporter:
    prom:
      factory:
        class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
      port: 9250
  reporters: prom
query:
  server:
    port: '6125'
s3:
  endpoint: http://seaweedfs:8333
  path:
    style:
      access: true
parallelism:
  default: 2
taskmanager:
  numberOfTaskSlots: 32
  memory:
    process:
      size: 8g
    managed:
      fraction: 0.8
env:
  java:
    opts:
      all: --add-exports=java.base/sun.net.util=ALL-UNNAMED --add-exports=java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED
execution:
  checkpointing:
    mode: EXACTLY_ONCE
    tolerable-failed-checkpoints: 50
    unaligned:
      enabled: true
    interval: 10min
    timeout: 10min
table:
  exec:
    mini-batch:
      size: 5000
      enabled: true
      allow-latency: 5s
    sink:
      require-on-conflict: false
    state:
      ttl: 1h
rest:
  bind-address: 0.0.0.0
  address: 0.0.0.0
