version: '3.8'
services:
  batch-etl:
    networks:
      ozone-analytics:
    image: mekomsolutions/ozone-flink-jobs-batch
    depends_on:
      analytics-migration:
        condition: service_completed_successfully
    environment:
      SOURCE_JDBC_URL: jdbc:mysql://${OPENMRS_DB_HOST}:${OPENMRS_DB_PORT}/${OPENMRS_DB_NAME}
      SOURCE_JDBC_USERNAME: root
      SOURCE_JDBC_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SINK_JDBC_URL: jdbc:postgresql://${ANALYTICS_DB_HOST}:${ANALYTICS_DB_PORT}/${ANALYTICS_DB_NAME}
      SINK_JDBC_USERNAME: ${ANALYTICS_DB_USER}
      SINK_JDBC_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      PROPERTIES_FILE: '/opt/flink/usrlib/job.properties'
      FLINK_CONF_DIR: '/etc/flink'
      JAVA_OPTS: '-XX:MaxRAMPercentage=80.0'
      ANALYTICS_QUERIES_PATH: /analytics/queries
      ANALYTICS_SOURCE_TABLES_PATH: /analytics/source-tables
      ANALYTICS_DB_NAME: ${ANALYTICS_DB_NAME}
      ANALYTICS_DB_USER: ${ANALYTICS_DB_USER}
      ANALYTICS_DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      ANALYTICS_DB_HOST: ${ANALYTICS_DB_HOST}
      ANALYTICS_DB_PORT: ${ANALYTICS_DB_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./flink/pipelines/job.properties:/opt/flink/usrlib/job.properties
      - ./flink/config/flink-conf.yaml:/etc/flink/flink-conf.yaml
      - ${ANALYTICS_QUERIES_PATH}:/analytics/queries
      - ${ANALYTICS_SOURCE_TABLES_PATH}:/analytics/source-tables
networks:
  ozone-analytics:
