version: '3.8'
services:
  minio:
    networks:
      ozone-analytics:
      web:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    ports:
      - "8090:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_NOTIFY_WEBHOOK_ENABLE: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT: http://minio-webhook:3000
    volumes:
      - ${MINIO_DATA_PATH:-storage-minio}:/data
    command: server --address ":9099" --console-address ":9000" /data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=${MINIO_CERT_RESOLVER}"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.middlewares.minio-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.minio.middlewares=superset-redirect-web-secure"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  minio-buckets:
    networks:
      ozone-analytics:
    build: ./minio-buckets
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      DEFAULT_BUCKETS: ${DEFAULT_BUCKETS}
      ANALYTICS_BUCKET: analytics
  minio-webhook:
     networks:
      ozone-analytics:
     build: ./minio-webhook
     environment:
       ACCESS_KEY: ${MINIO_ROOT_USER}
       ACCESS_SECRET: ${MINIO_ROOT_PASSWORD}
       DATA_BUCKET: analytics
     restart: unless-stopped


volumes:
  storage-minio:
  minio-config:
networks:
  ozone-analytics:
  web:
    external: true
    name: web