version: '3.8'
services:
  kowl:
    image: rsmnarts/kowl
    networks:
      - ozone-analytics
    container_name: "kowl"
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "echo \"$$KOWL_CONFIG_FILE\" > /tmp/config.yml; /app/kowl"
    ports:
      - "8282:8080"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      KOWL_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:9092"]
        connect:
          enabled: true
          clusters:
            - name: Ozone
              url: http://connect:8083
    depends_on:
      - "kafka"
      - "connect"
networks:
  ozone-analytics: