version: '3.8'
services:
  batch-etl:
    networks:
      ozone-analytics:
    image: mekomsolutions/ozone-flink-jobs-batch:2.5.0
    depends_on:
      analytics-migration:
        condition: service_completed_successfully
    environment:
      - ANALYTICS_SOURCE_TABLES_PATH=/analytics/source-tables
      - ANALYTICS_QUERIES_PATH=/analytics/queries
      - ANALYTICS_DB_NAME=${ANALYTICS_DB_NAME}
      - ANALYTICS_DB_USER=${ANALYTICS_DB_USER}
      - ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD}
      - ANALYTICS_DB_HOST=${ANALYTICS_DB_HOST}
      - ANALYTICS_DB_PORT=${ANALYTICS_DB_PORT}
      - ANALYTICS_KAFKA_URL=${ANALYTICS_KAFKA_URL}
      - OPENMRS_DB_NAME=${OPENMRS_DB_NAME}
      - OPENMRS_DB_USER=${OPENMRS_DB_USER}
      - OPENMRS_DB_PASSWORD=${OPENMRS_DB_PASSWORD}
      - OPENMRS_DB_HOST=${OPENMRS_DB_HOST}
      - OPENMRS_DB_PORT=${OPENMRS_DB_PORT}
      - ODOO_DB_NAME=${ODOO_DB_NAME:-odoo}
      - ODOO_DB_USER=${ODOO_DB_USER:-postgres}
      - ODOO_DB_PASSWORD=${ODOO_DB_PASSWORD:-password}
      - ODOO_DB_HOST=${ODOO_DB_HOST:-postgresql}
      - ODOO_DB_PORT=${ODOO_DB_PORT:-5432}
      - ANALYTICS_CONFIG_FILE_PATH=/analytics/config.yaml
      - JAVA_OPTS=${JAVA_OPTS}
      - NETWORK_MEMORY_MIN=${NETWORK_MEMORY_MIN:-1g}
      - NETWORK_MEMORY_MAX=${NETWORK_MEMORY_MAX:-1g}
      - TOTAL_PROCESS_MEMORY=${TOTAL_PROCESS_MEMORY:-8g}
      - MANAGED_MEMORY_FRACTION=${MANAGED_MEMORY_FRACTION:-0.7}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8084:8081"
    volumes:
      - ./flink/pipelines/job.properties:/opt/flink/usrlib/job.properties
      - ./flink/config/flink-conf.yaml:/etc/flink/flink-conf.yaml
      - ${ANALYTICS_QUERIES_PATH}:/analytics/queries
      - ${ANALYTICS_SOURCE_TABLES_PATH}:/analytics/source-tables
      - ${ANALYTICS_CONFIG_FILE_PATH}:/analytics/config.yaml
networks:
  ozone-analytics:
