version: '3.8'
services:
  parquet-export:
    networks:
      ozone-analytics:
    image: mekomsolutions/ozone-flink-parquet-export
    environment:
      JDBC_URL: jdbc:postgresql://${ANALYTICS_DB_HOST}:${ANALYTICS_DB_PORT}/${ANALYTICS_DB_NAME}
      JDBC_USERNAME: ${ANALYTICS_DB_USER}
      JDBC_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      LOCATION_TAG: ${LOCATION_TAG:-location1}
      FLINK_CONF_DIR: '/etc/flink'
      JAVA_OPTS: '-XX:MaxRAMPercentage=80.0'
      EXPORT_SOURCE_QUERIES_PATH: /export/queries
      EXPORT_DESTINATION_TABLES_PATH: /export/destination-tables
      ANALYTICS_DB_NAME: ${ANALYTICS_DB_NAME}
      ANALYTICS_DB_USER: ${ANALYTICS_DB_USER}
      ANALYTICS_DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      ANALYTICS_DB_HOST: ${ANALYTICS_DB_HOST}
      ANALYTICS_DB_PORT: ${ANALYTICS_DB_PORT}
      EXPORT_OUTPUT_TAG: ${EXPORT_OUTPUT_TAG}
      EXPORT_OUTPUT_PATH: /parquet
    volumes:
      - ./data/parquet:/parquet
      - ./flink/config/flink-conf.yaml:/etc/flink/flink-conf.yaml
      - ${EXPORT_DESTINATION_TABLES_PATH}:/export/destination-tables
      - ${EXPORT_SOURCE_QUERIES_PATH}:/export/queries
      - ${EXPORT_OUTPUT_PATH}:/parquet
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  ozone-analytics: