version: '3.8'
services:
  migrate:
    networks:
      ozone-analytics:
    restart: on-failure
    image: mekomsolutions/ozone-flink-jobs
    command: /run.sh
    environment:
      - FLINK_JOB_POSTGRES_USER=${ANALYTICS_DB_USER}
      - FLINK_JOB_POSTGRES_PASSWORD=${ANALYTICS_DB_PASSWORD}
      - FLINK_JOB_POSTGRES_URL=jdbc:postgresql://${ANALYTICS_DB_HOST}:${ANALYTICS_DB_PORT}/${ANALYTICS_DB_NAME}
      - FLINK_JOB_PROPERTIES_BOOTSTRAP_SERVERS=kafka:9092
  batch-etl:
    networks:
      ozone-analytics:
    image: mekomsolutions/ozone-flink-jobs-batch
    depends_on:
      - migrate
    environment:
      SOURCE_JDBC_URL: jdbc:mysql://mysql:3306/openmrs
      SOURCE_JDBC_USERNAME: root
      SOURCE_JDBC_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Admin123}
      SINK_JDBC_URL: jdbc:postgresql://${ANALYTICS_DB_HOST}:${ANALYTICS_DB_PORT}/${ANALYTICS_DB_NAME}
      SINK_JDBC_USERNAME: ${ANALYTICS_DB_USER}
      SINK_JDBC_PASSWORD: ${ANALYTICS_DB_PASSWORD}
      PROPERTIES_FILE: '/opt/flink/usrlib/job.properties'
      FLINK_CONF_DIR: '/etc/flink'
      JAVA_OPTS: '-XX:MaxRAMPercentage=80.0'
    volumes:
      - ./flink/pipelines/job.properties:/opt/flink/usrlib/job.properties
      - ./flink/config/flink-conf.yaml:/etc/flink/flink-conf.yaml
networks:
  ozone-analytics: