version: '3.8'
services:
  parquet-export:
    networks:
      ozone-analytics:
    image: mekomsolutions/ozone-flink-parquet-export
    environment:
      - ANALYTICS_DB_USER=${ANALYTICS_DB_USER}
      - ANALYTICS_DB_PASSWORD=${ANALYTICS_DB_PASSWORD}
      - ANALYTICS_DB_HOST=${ANALYTICS_DB_HOST}
      - ANALYTICS_DB_PORT=${ANALYTICS_DB_PORT}
      - ANALYTICS_DB_NAME=${ANALYTICS_DB_NAME}
      - EXPORT_OUTPUT_PATH=${EXPORT_OUTPUT_PATH}
      - EXPORT_OUTPUT_TAG=${EXPORT_OUTPUT_TAG}
      - ANALYTICS_CONFIG_FILE_PATH=/analytics/config.yaml
    volumes:
      - ./data/parquet:/parquet
      - ./flink/config/flink-conf.yaml:/etc/flink/flink-conf.yaml
      - ${EXPORT_DESTINATION_TABLES_PATH}:/export/destination-tables
      - ${EXPORT_SOURCE_QUERIES_PATH}:/export/queries
      - ${EXPORT_OUTPUT_PATH}:/parquet
      - ${ANALYTICS_CONFIG_FILE_PATH}:/analytics/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  ozone-analytics: