FROM maven:3.5-jdk-8-alpine as builder
# add pom.xml and source code
ADD ./pom.xml pom.xml
ADD ./src src/
RUN mvn clean install -Pbatch

FROM openjdk:8-jre-alpine
ENV OUTPUT_DIR=/parquet
COPY --from=builder target/ozone-etl-flink-1.0-SNAPSHOT-etl-export.jar etl-export.jar
ADD ./batch-export.sh ./batch-export.sh
CMD [ "/bin/sh","./batch-export.sh" ]
